[package]
name = "nova-driver"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
nova-source.workspace = true
nova-diagnostics.workspace = true
nova-ast.workspace = true
nova-hir.workspace = true
nova-lexer = { path = "../nova-lexer" }
nova-parser = { path = "../nova-parser" }

[dev-dependencies]
nova-resolve.workspace = true
nova-typecheck.workspace = true
nova-mir.workspace = true
nova-codegen.workspace = true
