[package]
name = "nova-typecheck"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
nova-hir.workspace = true
nova-resolve.workspace = true
nova-types.workspace = true
nova-source.workspace = true
nova-syntax.workspace = true
nova-diagnostics.workspace = true

[dev-dependencies]
nova-lexer = { path = "../nova-lexer" }
nova-parser = { path = "../nova-parser" }
